services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/population_trend:latest
    command: bash
    volumes:
      - $PWD:/workdir
  islasgeci_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: islasgeci/population_trend_dev:latest
    command: bash
    volumes:
      - $PWD:/workdir
